"""
Course description ingest.

Parses a Stern course catalog markdown file and writes the per-course
catalog description into public.courses.description. Descriptions are
keyed on (subject, catalog) and apply to every section of that course.

Source file format (one entry):

    COR1-GB.1102 Leadership (1.5)
    Course Description: <prose, possibly multi-line>
    [Pre-requisites:
    <optional prose>]
    Back to Top<Department Name>

We extract (subject, catalog, description) tuples and PATCH each matching
course row. A single PATCH affects all sections of the course.

Usage:
    python course_descriptions.py --md scripts/ingest/data/course_descriptions.md --dry-run
    python course_descriptions.py --md scripts/ingest/data/course_descriptions.md
    python course_descriptions.py --md ... --sql-out _course_descriptions.sql

For Spring 2027: re-run with the new term's catalog markdown.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from collections import Counter
from pathlib import Path
from typing import Any


# subject = uppercase letters/digits, dash, uppercase letters (e.g. ACCT-GB, COR1-GB)
# catalog = digits
# title is everything between catalog and (credits)
COURSE_HEADER_RE = re.compile(
    r"^\s*([A-Z][A-Z0-9]+-[A-Z]+)\.(\d+)\s+(.+?)\s*\(([\d.]+)\)\s*$"
)

# Lines that terminate a description block.
DESCRIPTION_TERMINATORS = ("Pre-requisites:", "Back to Top")


# ---- Parsing ---------------------------------------------------------

def parse_md(md_text: str) -> list[dict[str, Any]]:
    """Return one record per (subject, catalog) entry in the markdown."""
    lines = md_text.splitlines()
    records: list[dict[str, Any]] = []

    i = 0
    while i < len(lines):
        m = COURSE_HEADER_RE.match(lines[i])
        if not m:
            i += 1
            continue

        subject, catalog, title, credits_str = m.groups()
        i += 1

        # Skip blank lines until we hit "Course Description:" or another marker.
        while i < len(lines) and not lines[i].strip():
            i += 1

        description: str | None = None
        if i < len(lines) and lines[i].startswith("Course Description:"):
            first_line = lines[i][len("Course Description:"):].strip()
            desc_chunks: list[str] = [first_line] if first_line else []
            i += 1
            while i < len(lines):
                line = lines[i]
                if any(line.startswith(t) for t in DESCRIPTION_TERMINATORS):
                    break
                if COURSE_HEADER_RE.match(line):
                    break
                desc_chunks.append(line.strip())
                i += 1
            joined = " ".join(c for c in desc_chunks if c).strip()
            description = joined or None

        records.append({
            "subject":     subject,
            "catalog":     catalog,
            "title":       title.strip(),
            "credits":     float(credits_str),
            "description": description,
        })

    # Same (subject, catalog) can appear multiple times (e.g. 1.5- and 3-credit
    # variants). Keep the first non-empty description per key.
    deduped: dict[tuple[str, str], dict[str, Any]] = {}
    for r in records:
        key = (r["subject"], r["catalog"])
        existing = deduped.get(key)
        if existing is None:
            deduped[key] = r
        elif not existing["description"] and r["description"]:
            deduped[key] = r
    return list(deduped.values())


# ---- Output modes ----------------------------------------------------

def summarize(records: list[dict[str, Any]]) -> None:
    with_desc = sum(1 for r in records if r["description"])
    print(f"\nParsed {len(records)} unique (subject, catalog) entries; "
          f"{with_desc} have a non-empty description.")
    by_subject = Counter(r["subject"] for r in records)
    print("\nBy subject:")
    for subj, n in by_subject.most_common():
        print(f"  {subj:<10} {n}")


def sql_literal(v: Any) -> str:
    if v is None:
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"


def emit_sql(records: list[dict[str, Any]], out_path: Path) -> None:
    """One UPDATE per (subject, catalog). Skips entries without a description."""
    lines = [
        "-- Auto-generated by scripts/ingest/course_descriptions.py - do not hand-edit.",
    ]
    written = 0
    for r in records:
        if not r["description"]:
            continue
        lines.append(
            "UPDATE public.courses SET description = "
            f"{sql_literal(r['description'])} WHERE subject = "
            f"{sql_literal(r['subject'])} AND catalog = "
            f"{sql_literal(r['catalog'])};"
        )
        written += 1
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\nWrote {written} UPDATE statements to {out_path}")


def patch_via_supabase(records: list[dict[str, Any]]) -> None:
    """PATCH each (subject, catalog) row group via PostgREST.

    Uses stdlib urllib (matches fall_2026.py / syllabus_links.py).
    Reports matched vs. unmatched counts.
    """
    import urllib.error
    import urllib.parse
    import urllib.request

    try:
        from dotenv import load_dotenv  # type: ignore
    except ImportError:
        sys.exit(
            "Missing deps. From scripts/ingest/ run:\n"
            "    python -m pip install -r requirements.txt"
        )

    here = Path(__file__).parent
    load_dotenv(here / ".env")
    url = os.environ.get("SUPABASE_URL")
    key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY")
    if not url or not key:
        sys.exit(
            "Missing env. Set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY "
            "in scripts/ingest/.env (see README.md)."
        )

    base = f"{url.rstrip('/')}/rest/v1/courses"
    matched = 0
    unmatched: list[str] = []
    skipped = 0

    for r in records:
        if not r["description"]:
            skipped += 1
            continue
        qs = urllib.parse.urlencode({
            "subject": f"eq.{r['subject']}",
            "catalog": f"eq.{r['catalog']}",
        })
        endpoint = f"{base}?{qs}"
        payload = json.dumps({"description": r["description"]}).encode("utf-8")

        req = urllib.request.Request(
            endpoint,
            data=payload,
            method="PATCH",
            headers={
                "apikey": key,
                "Authorization": f"Bearer {key}",
                "Content-Type": "application/json",
                "Prefer": "return=representation",
            },
        )
        try:
            with urllib.request.urlopen(req) as resp:
                body = json.loads(resp.read().decode("utf-8") or "[]")
                if body:
                    matched += 1
                else:
                    unmatched.append(f"{r['subject']}.{r['catalog']}")
        except urllib.error.HTTPError as e:
            err_body = e.read().decode("utf-8", errors="replace")
            sys.exit(
                f"\nPATCH failed for {r['subject']}.{r['catalog']} "
                f"(HTTP {e.code}): {err_body}"
            )

    print(f"\nPatched {matched} (subject, catalog) groups; "
          f"{skipped} entries had no description.")
    if unmatched:
        print(f"\n{len(unmatched)} catalog entries had no matching course row "
              f"(course not offered this term, etc.):")
        for cid in unmatched[:20]:
            print(f"  {cid}")
        if len(unmatched) > 20:
            print(f"  ... +{len(unmatched) - 20} more")


# ---- Entrypoint ------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Course description ingest.")
    parser.add_argument(
        "--md",
        default=str(Path(__file__).parent / "data" / "course_descriptions.md"),
        help="Path to the catalog markdown "
             "(default: scripts/ingest/data/course_descriptions.md).",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Parse and summarize, but don't write anywhere.",
    )
    parser.add_argument(
        "--sql-out", metavar="FILE",
        help="Emit UPDATE statements to FILE instead of patching directly.",
    )
    args = parser.parse_args()

    md_path = Path(args.md)
    if not md_path.exists():
        sys.exit(f"Markdown not found: {md_path}")

    print(f"Reading {md_path}")
    records = parse_md(md_path.read_text(encoding="utf-8"))
    summarize(records)

    if args.dry_run:
        print("\n(dry-run - no writes)")
        return

    if args.sql_out:
        emit_sql(records, Path(args.sql_out))
        return

    patch_via_supabase(records)


if __name__ == "__main__":
    main()
