// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzlsqivbgojatxxvrywl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6bHNxaXZiZ29qYXR4eHZyeXdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzNDIzODcsImV4cCI6MjA4MzkxODM4N30.mg_zS1f2HAQVHDRXNTNPn7YjoIZFG2C1roNTgCgoeSk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});